[package]
name = "tulip"
version = "0.1.0"
authors = ["Romain Giot <romain.giot@u-bordeaux.fr>"]
crate-type = ["staticlib"]

[dependencies]
libc = "*"

[build-dependencies]
bindgen = "0.26.3"

[[bin]]
name = "graphmanipulation"
path = "demos/graphmanipulation.rs"
